place = input(" Give me a name of a place")
person = input(" Give me a name of person")
food = input(" Give me a name of a food")
adjective = input(" Give me an adjective")
bodypart = input(" Give me a bodypart")
stative_verb = input(" Give me a stative verb")
time = input( " Give me a unit of time")
noun = input( " Give me a noun")
adjective2= input( " Give me another adjective")


print(" I decided to go to " + place + " with " + person + ". When we got to" + place + " ,a clone of " + person + " was waiting for us." )
print(" We ran to a " + adjective + "convience store. When we got there, a(n) " + bodypart + " was thrown at " + person + "." )
print( " The" + bodypart + " was" + stative_verb + ". After that, we ran further from clone of " + person + " for " + time + " until we ran into a" + noun + ".")
print(" Following the meeting with" + noun + " commenced the most " + adjective2 + " food war the world had ever seen.")