noun = input(" give me a noun.")
food1 = input("give me a food.")
bodypart1  = input("give me a body part.")
adjective1 = input("Give me a place.")
place1 = input("Give me a place.")
jobtype1 = input("give me a job type.")
adjective2 = input("Give me an adjective.")
verb1 = input("Give nme a verb.")