noun1 = input("give me noun lil bro")
store1 = input ("Give me a store lil bro")
adjective1 = input("put in adjective lil bro")
verb1 = input("put in verb lil bro")
noun2 = input("put in noun lil bro I can see you")
number1= input("put in a number lil bro")
vichle1 = input("put in vichle lil bro")
print("I went to the mall to get a" + noun1)
print("I went to the" + store1 )
print("I saw a very" + adjective1 + "person")
print("they" + verb1 + "me and my son")
print("I bought a" + noun2)
print("It cost" + number1 + "dollars")
print("me and my son took a" + vichle1 + "home the end") 